version: '3.4'

services:
  sqlserver:
    image: microsoft/mssql-server-linux:2017-CU5
    environment:
      - SA_PASSWORD=admiN!123
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
  zoobook.hrm.api:
    image: ${DOCKER_REGISTRY-}zoobookhrmapi
    build:
      context: .
      dockerfile: ZooBook.Hrm.Api/Dockerfile
    ports:
      - "5055:443"
      - "5056:80"
    depends_on:
      - sqlserver
